version: '3.6'

x-app_base: &x-app_base
  tty: true
  stdin_open: true
  env_file: .env-docker
  working_dir: /app
  environment:
    - COMPOSE_HTTP_TIMEOUT=300
    - DEPENDENCY_TIMEOUT=${DEPENDENCY_TIMEOUT:-1000}
  networks:
    - internal_network
    - external_network
  volumes:
    - app_assets:/app/public
    - app_gems:/app/vendor/cache
    - bundle:/usr/local/bundle

services:
  # Base container to build for all other services
  base: &base
    <<: *x-app_base
    build:
      context: .
    container_name: code_fund_ads_base
    depends_on:
      - postgres
      - redis

  # App container
  app:
    <<: *x-app_base
    container_name: 'code_fund_ads-app'
    image: code_fund_ads_base:latest
    command: >
      bash -c "bundle exec rails tmp:clear &&
      bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
      - base
      # - webpacker

  webpacker:
    <<: *x-app_base
    container_name: 'code_fund_ads-webpacker'
    image: code_fund_ads_base:latest
    command: >
      bash -c "./bin/webpack-dev-server"
    ports:
      - '3035:3035'
    depends_on:
      - postgres
      - redis
      - base

  sidekiq:
    <<: *x-app_base
    container_name: 'code_fund_ads-sidekiq'
    image: code_fund_ads_base:latest
    command: bash -c 'bundle exec sidekiq'
    environment:
      - RAILS_ENV=test
    depends_on:
      - postgres
      - redis
      - base

  # Postgres
  postgres:
    container_name: 'code_fund_ads-postgres'
    image: postgres:11.3
    command: postgres -c max_locks_per_transaction=1024
    shm_size: '256mb'
    env_file: .env-docker
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - postgresconfig:/etc/postgresql
      - postgreslog:/var/log/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    networks:
      - internal_network

  # Redis
  redis:
    container_name: 'code_fund_ads-redis'
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - internal_network
    volumes:
      - 'redis:/data'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    sysctls:
      # https://github.com/docker-library/redis/issues/35
      net.core.somaxconn: '511'

networks:
  external_network:
  internal_network:
    internal: true

# persists the data in case you destroy your container
# Don't share node_modules because some packages a post_install call that has different results if installed with MacOS or Linux
volumes:
  app_assets:
  app_gems:
  bundle:
  postgresconfig:
  postgresdata:
  postgreslog:
  redis:
